$schema: "http://json-schema.org/draft-07/schema#"

description: Config File Schema

properties:
  preprocessing:
    description: Step Parametres
    type: object
    properties:
      tests: { type: string }
      cases: { type: string }
      deaths: { type: string }
    required: [ tests, cases, deaths ]
    additionalProperties: false

required: [ preprocessing ]
additionalProperties: false
